  
name: 'Test Build'

on:
  pull_request:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target /data \
          --docker-hub jpeterson37 \
          --branch master \
          --target agentdvr
